version: '3'
services:
  envoy:
    image: envoyproxy/envoy:v1.28-latest
    ports:
      - "10000:10000"
      - "9902:9902"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    develop:
      watch:
        - action: sync+restart
          path: ./envoy.yaml
  
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: ./
    
